# Module 4 - Case Study Problem 1 - Numpy

In [10]:
import numpy as np

def solve():
    y = []
    for i in range(2):
        y.append(int(input()))
    a = tuple(y)
    b = np.full(a,5)
    return b
print(solve())

3
3
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [7]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [11]:
array1 = np.random.randint(0,5,(3,3))
array2 = np.random.randint(0,5,(3,3))
array3 = np.random.randint(0,5,(3,3))

def array_sum():
    array4 = array1+array2+array3
    return array4

array_sum()

array([[ 8,  5,  8],
       [ 6,  6,  4],
       [ 9, 10,  7]])

In [15]:
arr = np.random.randint(0,100,(3,3))

def top_left(arr,m,n):
    print(arr)
    print(arr[0:m,:n])

top_left(arr,2,2)

[[10 81 93]
 [81 41 41]
 [ 7  1 63]]
[[10 81]
 [81 41]]


In [16]:
arr = np.random.randint(0,100,(3,3))
def bottom_right(arr,m,n):
    print(arr)
    print(arr[m:,n:])
    
bottom_right(arr,1,1)

[[20 68  3]
 [36 12 24]
 [93 75 49]]
[[12 24]
 [75 49]]


In [17]:
arr = np.array([1,1,1])
def mean_std():
    mn = np.mean(arr)
    sd = np.std(arr)
    res = {'Mean':mn, 'Std_dev':sd}
    return res
mean_std()   

{'Mean': 1.0, 'Std_dev': 0.0}