In [16]:
import numpy as np
def tu():
    y=[]
    for i in range(2):
        y.append(int(input()))
    a=tuple(y)
    b=np.full(a,5)
    return b
print(tu())

3
3
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [2]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [3]:
import numpy as np
def  solve(a, b):
    return np.full((a), b)
print(solve((3,3),5))

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [4]:
#2
a=np.array([[0,1,2,3],[4,5,6,7]])
b=np.array([[0,1,0,7]])
print(a+b)

[[ 0  2  2 10]
 [ 4  6  6 14]]


In [5]:
a=np.array([1,2,3,4,5,6,7,8,9])
x=a.reshape(3,3)
def top_left(a,m,n):
    print(a[m:,n:])
top_left(x,1,1)

[[5 6]
 [8 9]]


In [19]:
n= np.array([
    ['1','2','3'],
    ['4','5','6'],
    ['7','8','9'],
])
m = [n[0][:2],
     n[1][:2],
    ]
print(m)

[array(['1', '2'], dtype='<U1'), array(['4', '5'], dtype='<U1')]


In [7]:
arr=np.array([1,1,1])
n=np.mean(arr)
s=np.std(arr)
d={"Mean":n,"std_dev":s}
print(d)

{'Mean': 1.0, 'std_dev': 0.0}


In [8]:
mylist=[10,20,30,'apple',True,8.10]
mylist.extend([30,40])
print(mylist)

[10, 20, 30, 'apple', True, 8.1, 30, 40]


In [9]:
c=mylist[:-1]

In [10]:
print(c)

[10, 20, 30, 'apple', True, 8.1, 30]


In [11]:
n_t=(10,20,30,40,50)

In [12]:
min(n_t)

10

In [13]:
set1={1,2,3,4,5}
set2={2,4,6,8,9}
print(set1.union(set2))

{1, 2, 3, 4, 5, 6, 8, 9}


In [14]:
mylist=[10,20,30,'apple',True,8.10]
mylist.extend([30,40])
print(mylist)
c=mylist[::-1]

[10, 20, 30, 'apple', True, 8.1, 30, 40]


In [15]:
d={1:"data",2:"information",3:"text"}
print(d)


{1: 'data', 2: 'information', 3: 'text'}
