In [5]:
# 1 question---> Assignment module 4

import numpy as np
def tu():
    y = []
    for i in range(2):
        y.append(int(input()))
    a = tuple(y)
    b = np.full(a,5)
    return b
print(tu())

3
3
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [12]:
a = np.array([[0,1,2,3], [4,5,6,7]])
b = np.array([[2,5,8,6]])
print(a+b)

[[ 2  6 10  9]
 [ 6 10 14 13]]


In [28]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x = a.reshape(3,3)
def top_left(a,m,n):
    print(a[:m,:n])
top_left(x,2,2)

[[1 2]
 [4 5]]


In [ ]:
import numpy as np

arr = np.array([1,1,1])
n = np.mean(arr)
s = np.std(arr)
d = {"Mean":n ,"Std_dev":s}
print(d)

In [4]:
print(9999*9999)

99980001
